"""
Code Applier

Applies code changes generated by the Brain before execution by the Body.
"""

from pathlib import Path
from typing import Dict


class CodeApplier:
    """
    Applies code changes to the workspace.
    """

    def __init__(self, workspace_path: Path):
        self.workspace_path = Path(workspace_path)

    def apply(self, code_changes: Dict[str, str]) -> None:
        """
        Write code changes to the filesystem.
        
        Args:
            code_changes: Dict mapping relative file paths to new content.
        """
        for rel_path, content in code_changes.items():
            full_path = self.workspace_path / rel_path
            
            # Ensure parent directory exists
            full_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Write content
            with open(full_path, "w") as f:
                f.write(content)
            
            print(f"📝 Applied changes to {rel_path}")
